use std::fmt::Write as _;
use std::path::Path;

fn main() {
    tauri_build::build();
    embed_kits();

    // Windows/MSVC: give `cargo test` integration-test binaries the
    // Common-Controls v6 manifest they would otherwise never get. Without
    // it, a harness that links Tauri code importing `TaskDialogIndirect`
    // dies at load with STATUS_ENTRYPOINT_NOT_FOUND (0xc0000139) before a
    // single test runs — see src-tauri/tests-common-controls-v6.manifest.
    //
    // `-tests` and not the plain `rustc-link-arg`: this must never reach a
    // binary target. `tauri_build::build()` above already embeds a manifest
    // resource in `yames.exe`, and a second one fails the link with
    // `CVT1100: duplicate resource` / `LNK1123`.
    //
    // Cargo has no equivalent key for the `--lib` unit-test harness, so that
    // one is handled by `RUSTFLAGS` in `.github/workflows/ci.yml` and in
    // `scripts/rust-test.mjs` — `cargo test --lib` builds no bins, so
    // setting it for that invocation alone is safe.
    #[cfg(all(windows, target_env = "msvc"))]
    {
        let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests-common-controls-v6.manifest");
        println!("cargo:rerun-if-changed=tests-common-controls-v6.manifest");
        println!("cargo:rustc-link-arg-tests=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg-tests=/MANIFESTINPUT:{}",
            manifest.display()
        );
    }
}

/// ADDING A KIT IS ADDING A FOLDER.
///
/// The five synthesised kits used to be forty `include_bytes!` lines and a
/// hand-written table in `engine.rs`, with the column order of the table
/// and the order of an enum held together by a test. A recorded kit is a
/// hundred and thirty-two files, and two of them are on the way
/// (`plans/JAM_SOUND.md` §5), so the table stops being something a person
/// writes.
///
/// This walks `sounds/kits/*/kit.json`, and for every folder it finds
/// writes an entry into `$OUT_DIR/kits_generated.rs`: the manifest as a
/// string constant and one `include_bytes!` per WAV beside it, keyed by
/// file name. `kit.rs` `include!`s the result and parses the manifests with
/// the same code it uses on a folder the musician points at, so a shipped
/// kit and somebody's own sample folder go through one loader.
///
/// It does NOT validate the manifests. A missing voice, a layer that is not
/// there, a rate the file disagrees with — all of those are the loader's to
/// report as a sentence at run time, and a build that refuses to compile
/// because a kit folder is half-written is a worse day than one that says
/// so when the kit is chosen.
fn embed_kits() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("sounds/kits");
    // A new kit folder, a new WAV in one, or an edited manifest all have to
    // re-run this. Watching the directory itself is what notices a folder
    // appearing; watching each folder is what notices a file inside one.
    println!("cargo:rerun-if-changed=sounds/kits");

    let mut dirs: Vec<_> = std::fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("sounds/kits is not readable: {e}"))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.join("kit.json").is_file())
        .collect();
    // Sorted, so the generated file is the same bytes on every machine and
    // a kit's index does not depend on the order the filesystem answered
    // in. Kit ids are looked up by name, but the ORDER is what the picker
    // shows and what a test can name.
    dirs.sort();

    let mut out = String::from(
        "// Generated by build.rs from sounds/kits/*/kit.json. Do not edit.\n\
         pub static SHIPPED_KITS: &[ShippedKit] = &[\n",
    );
    for dir in &dirs {
        let name = dir.file_name().expect("a kit folder has a name");
        println!("cargo:rerun-if-changed=sounds/kits/{}", name.to_string_lossy());
        let manifest = dir.join("kit.json");
        writeln!(out, "    ShippedKit {{").unwrap();
        writeln!(
            out,
            "        manifest: include_str!(r\"{}\"),",
            manifest.display()
        )
        .unwrap();
        writeln!(out, "        files: &[").unwrap();
        let mut wavs: Vec<_> = std::fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("{} is not readable: {e}", dir.display()))
            .flatten()
            .map(|e| e.path())
            .filter(|p| {
                p.extension()
                    .is_some_and(|e| e.eq_ignore_ascii_case("wav"))
            })
            .collect();
        wavs.sort();
        for wav in wavs {
            let file = wav.file_name().expect("a WAV has a name").to_string_lossy();
            writeln!(
                out,
                "            (\"{}\", include_bytes!(r\"{}\")),",
                file.to_ascii_lowercase(),
                wav.display()
            )
            .unwrap();
        }
        writeln!(out, "        ],\n    }},").unwrap();
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("kits_generated.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("could not write {}: {e}", dest.display()));
}
