/// The commands the frontend may call. `tauri-plugin` turns each into an
/// autogenerated permission under `permissions/autogenerated/commands/`, and
/// `permissions/default.toml` is what `capabilities/mobile.json` grants.
const COMMANDS: &[&str] = &[
    "set_background_audio",
    "keep_awake",
    "open_url",
    "set_back_intercept",
    "set_event_channel",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
