/// The commands the frontend may call. `tauri-plugin` turns each into an
/// autogenerated permission under `permissions/autogenerated/commands/`, and
/// `permissions/default.toml` is what `capabilities/mobile.json` grants.
const COMMANDS: &[&str] = &[
    "set_background_audio",
    "keep_awake",
    "open_url",
    "set_back_intercept",
    "set_event_channel",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        // The Swift half. Only ever looked at when the *host* is macOS and the
        // target is iOS — `tauri-plugin`'s own arm for it is `#[cfg(target_os =
        // "macos")]` — so naming it here costs an Android or desktop build
        // nothing.
        .ios_path("ios")
        .build();
}
